"""Add image field.

Revision ID: 2d2881f1281a
Revises: 21a91390fdf7
Create Date: 2022-10-16 23:17:45.780453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d2881f1281a'
down_revision = '21a91390fdf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('image', sa.Unicode(length=128)))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'image')
    # ### end Alembic commands ###
